# Generated by Django 5.2.1 on 2025-05-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(default='Resum no disponible'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_name',
            field=models.CharField(default='etiqueta', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
