# Generated by Django 5.2.1 on 2025-05-28 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_author_bio_alter_author_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 1, 12, 0)),
            preserve_default=False,
        ),
    ]
