name: build-docs

on:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Django

      - name: Create docs folder
        run: mkdir -p docs

      - name: Generate docs with Pydoc
        env:
          DJANGO_SETTINGS_MODULE: my_site.settings
        run: |
          python manage.py shell -c "import pydoc; import blog.models; pydoc.writedoc(blog.models)"
          python manage.py shell -c "import pydoc; import blog.views; pydoc.writedoc(blog.views)"
          python manage.py shell -c "import pydoc; import blog.urls; pydoc.writedoc(blog.urls)"

      - name: Move docs to folder
        run: |
          mv blog.models.html docs/
          mv blog.views.html docs/
          mv blog.urls.html docs/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs

